export const languages = [
  {
    id: "en",
    name: "English",
    nativeName: "English",
    locale: "en-US",
    flag: "🇺🇸",
    rtl: false,
    isDefault: true,
  },
  {
    id: "uz",
    name: "Uzbek",
    nativeName: "O'zbek",
    locale: "uz-UZ",
    flag: "🇺🇿",
    rtl: false,
    isDefault: false,
  },
  {
    id: "ru",
    name: "Russian",
    nativeName: "Русский",
    locale: "ru-RU",
    flag: "🇷🇺",
    rtl: false,
    isDefault: false,
  },
  {
    id: "tr",
    name: "Turkish",
    nativeName: "Türkçe",
    locale: "tr-TR",
    flag: "🇹🇷",
    rtl: false,
    isDefault: false,
  },
  {
    id: "de",
    name: "German",
    nativeName: "Deutsch",
    locale: "de-DE",
    flag: "🇩🇪",
    rtl: false,
    isDefault: false,
  },
  {
    id: "fr",
    name: "French",
    nativeName: "Français",
    locale: "fr-FR",
    flag: "🇫🇷",
    rtl: false,
    isDefault: false,
  },
  {
    id: "es",
    name: "Spanish",
    nativeName: "Español",
    locale: "es-ES",
    flag: "🇪🇸",
    rtl: false,
    isDefault: false,
  },
  {
    id: "pt",
    name: "Portuguese",
    nativeName: "Português",
    locale: "pt-PT",
    flag: "🇵🇹",
    rtl: false,
    isDefault: false,
  },
  {
    id: "ar",
    name: "Arabic",
    nativeName: "العربية",
    locale: "ar-SA",
    flag: "🇸🇦",
    rtl: true,
    isDefault: false,
  },
  {
    id: "zh",
    name: "Chinese",
    nativeName: "中文",
    locale: "zh-CN",
    flag: "🇨🇳",
    rtl: false,
    isDefault: false,
  },
  {
    id: "ja",
    name: "Japanese",
    nativeName: "日本語",
    locale: "ja-JP",
    flag: "🇯🇵",
    rtl: false,
    isDefault: false,
  },
  {
    id: "ko",
    name: "Korean",
    nativeName: "한국어",
    locale: "ko-KR",
    flag: "🇰🇷",
    rtl: false,
    isDefault: false,
  },
];
